
package scalatags
package jsdom
import acyclic.file
import org.scalajs.dom
import scalatags.generic.Util
trait Tags extends generic.Tags[dom.Element, dom.Element, dom.Node]{
  // Root Element
  val html = "html".tag[dom.html.Html]
  // Document Metadata
  val head = "head".tag[dom.html.Head]
  val base = "base".voidTag[dom.html.Base]
  val link = "link".voidTag[dom.html.Link]
  val meta = "meta".voidTag[dom.html.Meta]
  // Scripting
  val script = "script".tag[dom.html.Script]
  // Sections
  val body = "body".tag[dom.html.Body]
  val h1 = "h1".tag[dom.html.Heading]
  val h2 = "h2".tag[dom.html.Heading]
  val h3 = "h3".tag[dom.html.Heading]
  val h4 = "h4".tag[dom.html.Heading]
  val h5 = "h5".tag[dom.html.Heading]
  val h6 = "h6".tag[dom.html.Heading]
  val header = "header".tag[dom.html.Element]
  val footer = "footer".tag[dom.html.Element]
  // Grouping content
  val p = "p".tag[dom.html.Paragraph]
  val hr = "hr".voidTag[dom.html.HR]
  val pre = "pre".tag[dom.html.Pre]
  val blockquote = "blockquote".tag[dom.html.Quote]
  val ol = "ol".tag[dom.html.OList]
  val ul = "ul".tag[dom.html.UList]
  val li = "li".tag[dom.html.LI]
  val dl = "dl".tag[dom.html.DList]
  val dt = "dt".tag[dom.html.DT]
  val dd = "dd".tag[dom.html.DD]
  val figure = "figure".tag[dom.html.Element]
  val figcaption = "figcaption".tag[dom.html.Element]
  val div = "div".tag[dom.html.Div]
  // Text-level semantics
  val a = "a".tag[dom.html.Anchor]
  val em = "em".tag[dom.html.Element]
  val strong = "strong".tag[dom.html.Element]
  val small = "small".tag[dom.html.Element]
  val s = "s".tag[dom.html.Element]
  val cite = "cite".tag[dom.html.Element]
  val code = "code".tag[dom.html.Element]
  val sub = "sub".tag[dom.html.Element]
  val sup = "sup".tag[dom.html.Element]
  val i = "i".tag[dom.html.Element]
  val b = "b".tag[dom.html.Element]
  val u = "u".tag[dom.html.Element]
  val span = "span".tag[dom.html.Span]
  val br = "br".voidTag[dom.html.BR]
  val wbr = "wbr".voidTag[dom.html.Element]
  // Edits
  val ins = "ins".tag[dom.html.Mod]
  val del = "del".tag[dom.html.Mod]
  // Embedded content
  val img = "img".voidTag[dom.html.Image]
  val iframe = "iframe".tag[dom.html.IFrame]
  val embed = "embed".voidTag[dom.html.Embed]
  val `object` = "object".tag[dom.html.Object]
  val param = "param".voidTag[dom.html.Param]
  val video = "video".tag[dom.html.Video]
  val audio = "audio".tag[dom.html.Audio]
  val source = "source".voidTag[dom.html.Source]
  val track = "track".voidTag[dom.html.Track]
  val canvas = "canvas".tag[dom.html.Canvas]
  val map = "map".tag[dom.html.Map]
  val area = "area".voidTag[dom.html.Area]
  // Tabular data
  val table = "table".tag[dom.html.Table]
  val caption = "caption".tag[dom.html.TableCaption]
  val colgroup = "colgroup".tag[dom.html.TableCol]
  val col = "col".voidTag[dom.html.TableCol]
  val tbody = "tbody".tag[dom.html.TableSection]
  val thead = "thead".tag[dom.html.TableSection]
  val tfoot = "tfoot".tag[dom.html.TableSection]
  val tr = "tr".tag[dom.html.TableRow]
  val td = "td".tag[dom.html.TableCell]
  val th = "th".tag[dom.html.TableHeaderCell]
  // Forms
  val form = "form".tag[dom.html.Form]
  val fieldset = "fieldset".tag[dom.html.FieldSet]
  val legend = "legend".tag[dom.html.Legend]
  val label = "label".tag[dom.html.Label]
  val input = "input".voidTag[dom.html.Input]
  val button = "button".tag[dom.html.Button]
  val select = "select".tag[dom.html.Select]
  val datalist = "datalist".tag[dom.html.DataList]
  val optgroup = "optgroup".tag[dom.html.OptGroup]
  val option = "option".tag[dom.html.Option]
  val textarea = "textarea".tag[dom.html.TextArea]
}
