package scalatags
package text
trait Tags extends generic.Tags[Builder, String, String] with TagFactory {
  // Root Element
  lazy val html: ConcreteHtmlTag[String] = tag("html")
  // Document Metadata
  lazy val head: ConcreteHtmlTag[String] = tag("head")
  lazy val base: ConcreteHtmlTag[String] = tag("base", void = true)
  lazy val link: ConcreteHtmlTag[String] = tag("link", void = true)
  lazy val meta: ConcreteHtmlTag[String] = tag("meta", void = true)
  // Scripting
  lazy val script: ConcreteHtmlTag[String] = tag("script")
  // Sections
  lazy val body: ConcreteHtmlTag[String] = tag("body")
  lazy val h1: ConcreteHtmlTag[String] = tag("h1")
  lazy val h2: ConcreteHtmlTag[String] = tag("h2")
  lazy val h3: ConcreteHtmlTag[String] = tag("h3")
  lazy val h4: ConcreteHtmlTag[String] = tag("h4")
  lazy val h5: ConcreteHtmlTag[String] = tag("h5")
  lazy val h6: ConcreteHtmlTag[String] = tag("h6")
  lazy val header: ConcreteHtmlTag[String] = tag("header")
  lazy val footer: ConcreteHtmlTag[String] = tag("footer")
  // Grouping content
  lazy val p: ConcreteHtmlTag[String] = tag("p")
  lazy val hr: ConcreteHtmlTag[String] = tag("hr", void = true)
  lazy val pre: ConcreteHtmlTag[String] = tag("pre")
  lazy val blockquote: ConcreteHtmlTag[String] = tag("blockquote")
  lazy val ol: ConcreteHtmlTag[String] = tag("ol")
  lazy val ul: ConcreteHtmlTag[String] = tag("ul")
  lazy val li: ConcreteHtmlTag[String] = tag("li")
  lazy val dl: ConcreteHtmlTag[String] = tag("dl")
  lazy val dt: ConcreteHtmlTag[String] = tag("dt")
  lazy val dd: ConcreteHtmlTag[String] = tag("dd")
  lazy val figure: ConcreteHtmlTag[String] = tag("figure")
  lazy val figcaption: ConcreteHtmlTag[String] = tag("figcaption")
  lazy val div: ConcreteHtmlTag[String] = tag("div")
  // Text-level semantics
  lazy val a: ConcreteHtmlTag[String] = tag("a")
  lazy val em: ConcreteHtmlTag[String] = tag("em")
  lazy val strong: ConcreteHtmlTag[String] = tag("strong")
  lazy val small: ConcreteHtmlTag[String] = tag("small")
  lazy val s: ConcreteHtmlTag[String] = tag("s")
  lazy val cite: ConcreteHtmlTag[String] = tag("cite")
  lazy val code: ConcreteHtmlTag[String] = tag("code")
  lazy val sub: ConcreteHtmlTag[String] = tag("sub")
  lazy val sup: ConcreteHtmlTag[String] = tag("sup")
  lazy val i: ConcreteHtmlTag[String] = tag("i")
  lazy val b: ConcreteHtmlTag[String] = tag("b")
  lazy val u: ConcreteHtmlTag[String] = tag("u")
  lazy val span: ConcreteHtmlTag[String] = tag("span")
  lazy val br: ConcreteHtmlTag[String] = tag("br", void = true)
  lazy val wbr: ConcreteHtmlTag[String] = tag("wbr", void = true)
  // Edits
  lazy val ins: ConcreteHtmlTag[String] = tag("ins")
  lazy val del: ConcreteHtmlTag[String] = tag("del")
  // Embedded content
  lazy val img: ConcreteHtmlTag[String] = tag("img", void = true)
  lazy val iframe: ConcreteHtmlTag[String] = tag("iframe")
  lazy val embed: ConcreteHtmlTag[String] = tag("embed", void = true)
  lazy val `object`: ConcreteHtmlTag[String] = tag("object")
  lazy val param: ConcreteHtmlTag[String] = tag("param", void = true)
  lazy val video: ConcreteHtmlTag[String] = tag("video")
  lazy val audio: ConcreteHtmlTag[String] = tag("audio")
  lazy val source: ConcreteHtmlTag[String] = tag("source", void = true)
  lazy val track: ConcreteHtmlTag[String] = tag("track", void = true)
  lazy val canvas: ConcreteHtmlTag[String] = tag("canvas")
  lazy val map: ConcreteHtmlTag[String] = tag("map")
  lazy val area: ConcreteHtmlTag[String] = tag("area", void = true)
  // Tabular data
  lazy val table: ConcreteHtmlTag[String] = tag("table")
  lazy val caption: ConcreteHtmlTag[String] = tag("caption")
  lazy val colgroup: ConcreteHtmlTag[String] = tag("colgroup")
  lazy val col: ConcreteHtmlTag[String] = tag("col", void = true)
  lazy val tbody: ConcreteHtmlTag[String] = tag("tbody")
  lazy val thead: ConcreteHtmlTag[String] = tag("thead")
  lazy val tfoot: ConcreteHtmlTag[String] = tag("tfoot")
  lazy val tr: ConcreteHtmlTag[String] = tag("tr")
  lazy val td: ConcreteHtmlTag[String] = tag("td")
  lazy val th: ConcreteHtmlTag[String] = tag("th")
  // Forms
  lazy val form: ConcreteHtmlTag[String] = tag("form")
  lazy val fieldset: ConcreteHtmlTag[String] = tag("fieldset")
  lazy val legend: ConcreteHtmlTag[String] = tag("legend")
  lazy val label: ConcreteHtmlTag[String] = tag("label")
  lazy val input: ConcreteHtmlTag[String] = tag("input", void = true)
  lazy val button: ConcreteHtmlTag[String] = tag("button")
  lazy val select: ConcreteHtmlTag[String] = tag("select")
  lazy val datalist: ConcreteHtmlTag[String] = tag("datalist")
  lazy val optgroup: ConcreteHtmlTag[String] = tag("optgroup")
  lazy val option: ConcreteHtmlTag[String] = tag("option")
  lazy val textarea: ConcreteHtmlTag[String] = tag("textarea")
}
